# Generated by Django 6.0.6 on 2026-06-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rasm', models.ImageField(upload_to='products/')),
                ('tavsif', models.TextField()),
            ],
        ),
    ]
