# Generated by Django 6.0.6 on 2026-06-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='kategoriya',
            field=models.CharField(choices=[('fruits', 'Fruits & Veges'), ('juices', 'Juices'), ('bolalar', 'Bolalar Uchun'), ('aksiyalar', 'Haftalik Aksiyalar')], default='fruits', max_length=50),
        ),
    ]
